# Site settings test

title: Project Pages
header-img: img/home-bg.jpg
email: specialnamin@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/SRL251"
url: "http://naminz.github.io"
github_username: Naminz
project_repository: SRL251
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
